version: '3.3'
services:
  database:
    image: amsterdam/postgres11
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: externaldata
      POSTGRES_USER: externaldata
      POSTGRES_PASSWORD: insecure
    volumes:
      - ~/.ssh/datapunt.key:/root/.ssh/datapunt.key
      - ./backups:/tmp/backups

  import:
    build: ./import
    links:
      - database
    environment:
      - PYTHONPATH=/app

  api:
    build: ./api
    ports:
      - "8001:8001"
    links:
      - database
    environment:
      - DATABASE_NAME=externaldata
      - DATABASE_PASSWORD=insecure
      - UWSGI_HTTP=0.0.0.0:8001
      - UWSGI_MASTER=1
      - UWSGI_STATIC_INDEX=index.html
      - UWSGI_STATIC_MAP=/externaldata/static=/static
      - UWSGI_CALLABLE=application
      - UWSGI_VACUUM=1
      - UWSGI_STATIC_EXPIRES=/* 3600
      - UWSGI_OFFLOAD_THREADS=1
      - UWSGI_HARAKIRI=15
      - UWSGI_DIE_ON_TERM=1
      - UWSGI_MODULE=wsgi:application

  mapserver:
    build: 
      context: mapserver/
      dockerfile: Dockerfile_noproxy
    ports:
      - "8070:80"
    links:
      - database

    environment:
      EXTERNALDATA_DB_HOST: database
      EXTERNALDATA_DB_NAME: externaldata
      EXTERNALDATA_DB_USER: externaldata
      EXTERNALDATA_DB_PASSWORD: insecure
      MAP_URL: "http://mapserver"
      LEGEND_URL: "http://mapserver"
